<?xml version="3.0" encoding="UTF-8"?>

<simulation-properties version="2.0" application="asj-3.0.0" x="198" y="55" width="387" height="160">
  <property name="left" value="0.0" input="true" output="true">
    <plotter enabled="false" min="0.0" max="100.0" window="left" representing="left" color="16711680"/>
  </property>
  <property name="level" value="0.0" input="true" output="true">
    <plotter enabled="false" min="0.0" max="100.0" window="level" representing="level" color="16711680"/>
  </property>
</simulation-properties>