<?xml version="3.0" encoding="UTF-8"?>

<simulation-properties version="2.0" application="asj-3.0.0" x="1080" y="202" width="353" height="203">
  <property name="level" value="0.0" input="true" output="true">
    <plotter enabled="false" min="0.0" max="100.0" window="level" representing="level" color="16711680"/>
  </property>
  <property name="score" value="11.0" input="true" output="true">
    <plotter enabled="false" min="0.0" max="100.0" window="score" representing="score" color="16711680"/>
  </property>
</simulation-properties>